### ISSUE TITLE
Поиск

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#14]
Не работает поиск. Сделать так, чтобы он работал.  (Любой поиск прикрутить , хоть бы Яндекс работал. Выводил результаты поиска на внутренней странице.) “ site:hochy.by суши “

На главной странице вверху справа

**Comment by vk26** [comment]
Сделал поиск по наименованию кафе. Прикрутил автокомплит при вводе в поле поиска. Использовал typehead.js.
