### ISSUE TITLE
Лучшие предложения

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#15]
1)Не работает предложение. Настроить его, чтобы оно вело на соответствующий ресторан.
2)Лучшие предложения :  изменить на Акционные предложения
3)Картинка вылезает за края рамки. Сделать border 
Так-же под кнопкой вылазит текст, его убрать.

![77777](https://cloud.githubusercontent.com/assets/4678664/7100823/4ce3644c-e03f-11e4-955a-d37430eb7c66.png)

**Comment by vk26** [comment]
Ссылка на акцию не работала, потому что для кафе не установлен признак is_visible. Стоит его включить для кафе, акционная ссылка заработает. Внес [изменения](https://github.com/EijiMirai/pizza/blob/3a2f4ba798d5a1e7af6feef206e06ff2f6be838b/app/models/cafe_action.rb#L11), чтобы публикуемая акция выводилась, если для кафе включена видимость.
