### ISSUE TITLE
User/adresses

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#16]
При вводе текста текст уходит за контейнер и его не видно, сделать чтобы окошко с вводимым текстом расширялось вниз. 

![9999](https://cloud.githubusercontent.com/assets/4678664/7100826/9594a67e-e03f-11e4-8977-f45a7794d527.png)

**Comment by EijiMirai** [comment]
Исправил [внешний вид](https://github.com/EijiMirai/pizza/commit/fcfa9f87bb8d430a70f83bfcb0036cf7ee4c7cc8), но не стал делать автоматическое изменение высоты потому что:
* Это оказалось крайне геморройным
* Это будет портить эстетическую картину
