### ISSUE TITLE
Классы ресторанов, из 15 отображается 15.

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#18]
При выборе всех классов ресторанов, т.е. по логике их должно быть 15, отображается 14. Просто заметил.

**Comment by EijiMirai** [comment]
Не понял...
Какие классы?
Где выбираешь?

**Comment by vk26** [comment]
проверил, фильтр по классам кафе работает. Просто для многих кафе класс (эконом/средний/премиум) не выбран, соответственно в отбор не попадают, когда выбирают все 3 класса. Нужно установить классы для всех кафе, где не проставлено.

**Comment by EijiMirai** [comment]
Думаю что @iLucker93 необходимо объяснить этот момент клиенту.
