### ISSUE TITLE
Удаление блюд из админки - ошибка 

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#20]
После удаления нескольких блюд из админки, перестали отображаться меню в кафе.

**Comment by EijiMirai** [comment]
@vk26 - отпишись здесь о статусе и реализации таска.

**Comment by iLucker93** [comment]
Необходимо чтобы пользователь мог ввести сумму собственноручно, и она округлилась до 10тысяч. 
![qqqqq](https://cloud.githubusercontent.com/assets/4678664/7101784/f0adcd2e-e071-11e4-9353-04ca0a5da9e8.jpg)

**Comment by EijiMirai** [comment]
**[Done](https://github.com/EijiMirai/pizza/commit/db49d82b2ad95dce6ee01c6d5fc88348d1b9f679)**
