### ISSUE TITLE
Чекбокс с суммой заказа

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#21]
Кликабельное окошко для суммы. Пользователь может подумать, что сумму следует ввести с клавиатуры. Что вполне можно сделать.

![31](https://cloud.githubusercontent.com/assets/4678664/7101240/a8d3862a-e057-11e4-8f53-0e47402d7a73.png)

После чего возникает ошибка.  : 
![32](https://cloud.githubusercontent.com/assets/4678664/7101238/8bf52cfc-e057-11e4-9c5e-1902a5a13469.png)

**Comment by iLucker93** [comment]
![31](https://cloud.githubusercontent.com/assets/4678664/7101240/a8d3862a-e057-11e4-8f53-0e47402d7a73.png)

**Comment by EijiMirai** [comment]
Судя по всему @vk26 уже реализовал функционал.
Закрываю до выяснения статуса с клиентом.

**Comment by vk26** [comment]
да, это я уже сделал давно.

**Comment by EijiMirai** [comment]
Не видел где ты это сделал. Поэтому сделал сам)
