### ISSUE TITLE
Ошибка при заказе из разных кафе 

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#23]
![444](https://cloud.githubusercontent.com/assets/4678664/7101320/5fe3747a-e05c-11e4-9aab-0fb8ab5f067c.png)

**Comment by EijiMirai** [comment]
Кажется @vk26 исправил, но не уверен что так как хотелось бы клиенту.

Пока что закрываю и надеюсь что клиент не будет против =)
