### ISSUE TITLE
Сделать страничку Инфо

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#24]
Месторасположение :  http://www.hochy.by/cafes/gruzin   

Что должно быть:
1)инфо о доставке
2)о кафе 
3)о ценах 

Эту инфу должен добавлять админ, и пользователи могли просматривать тут : http://www.hochy.by/cafes/gruzin    ( клацали кнопку инфо и она отображалась)

**Comment by EijiMirai** [comment]
**Done**
