### ISSUE TITLE
Скрыть О НАС

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#5]
Скрыть

**Comment by EijiMirai** [comment]
Сейчас там стоит просто ссылка на '#'

Если нужно будет сделать ссылку на страницу **[about_us](http://hochy.by/about_us)**, то откроем таск и переделаем.

Делается это [здесь](https://github.com/EijiMirai/pizza/blob/master/app/views/partials/_footer.html.erb#L4-L11)

**Comment by iLucker93** [comment]
Тупо скрыть "О нас"  Чтобы на том месте был фон

**Comment by EijiMirai** [comment]
**[Done](https://github.com/EijiMirai/pizza/commit/39615ccff58d705e0878a6993e48af200c6d10bc)**
