### ISSUE TITLE
4) В личном кабинете отключить “Призы”

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#6]
В личном кабинете отключить “Призы”

**Comment by EijiMirai** [comment]
**Done**

Полностью закомментиовал данные в файлах:
[prizes.rb](https://github.com/EijiMirai/pizza/blob/master/app/admin/prizes.rb)
и
[prizes_categories.rb](https://github.com/EijiMirai/pizza/blob/master/app/admin/prizes_categories.rb)
