### ISSUE TITLE
1) Footer    social buttons 

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#7]
пусть все социальные кнопки  ведут пока в наш паблик - а в нем я сделаю пост про новый наш сервис Hochy.by
https://vk.com/megarost_org

**Comment by EijiMirai** [comment]
**Done**

[Закомментировал](https://github.com/EijiMirai/pizza/issues?q=is%3Aissue+milestone%3A%22Block+one%22+is%3Aclosed) ненужные кнопки, а в оставшейся проставил ссылку.
