### ISSUE TITLE
Благодарность за заказ

### ISSUE THREAD

**Issue by iLucker93** [EijiMirai/pizza#9]
После того как клиент сделал заказ. 

![sdfsdf](https://cloud.githubusercontent.com/assets/4678664/7100783/18fd0f6c-e03e-11e4-8d23-3c6bc5181a12.jpg)

**Comment by EijiMirai** [comment]
**Done**

Пришлось переписать сторонний гем и обновить ruby с *1.9.3-p488* до *2.1.2*, но, вроде как, теперь всё работает. И, надеюсь, не поломается в один прекрасный день :santa:
